### ISSUE TITLE
Interaction with cookie banners

### ISSUE THREAD

**Issue by sana-17** [UWCSESecurityLab/adscraper#6]
Is there an option or a potential extension to this scraper where it can also interact with cookie banners on websites? Most of the websites load dynamic advertisements only when you interact with their cookie banners and infact in other cases the whole landing page of websites are covered with cookie banners and that scraping attempt just goes to waste as it does not scrape any ads and sometimes even screenshots that cookie banner itself. Any suggestions/hints would be helpful. Thanks

**Comment by eric-zeng** [comment]
Thanks for the suggestion - there's no current mechanism for removing cookie banners, but it seems like this could be a good feature to add. One approach could be to use the CSS Selectors in Fanboy's Anti-Cookie filter list (https://fanboy.co.nz/) to find and delete/hide matching elements. I may look at this next month but can't make any promises at the moment.

**Comment by eric-zeng** [comment]
Added support for removing cookie banners in commit [4577e61](https://github.com/UWCSESecurityLab/adscraper/commit/4577e613a8e9a08e27b57bc1fcdb2a50e952fc79), just merged into main branch.
